import time


### MAD LIBS ###
### Source: https://i.pinimg.com/736x/4f/d2/fd/4fd2fdcd1a24611d0bbd238876096bbe--outer-space-camp-mad-libs-for-adults.jpg ###
### Ask Questions Here ###
print("write and adjective")
adjective1 = input()
print("write a noun")
noun1 = input()
print("write a adjective")
adjective2 = input()
print("write a plural noun")
pluralnoun1 = input()
print ("write an adverb")
adverb1 = input()
print ("write a verb ending in 'ing'")
verbing1 = input()
print("write a plural silly word")
sillywordplural1 = input()
print("write an adjective")
adjective3 = input()
print ("write a plural noun")
pluralnoun2 = input()
print("write tyour first name")
firstname1 = input()
print("write an adjective")
adjective4 = input()
print("write a number")
number1 = input()
print("write another first name")
firstname2 = input()
print("write another first name")
firstname3 = input()
print("wriate another first name")
firstname4 = input()
print("wriate another first name")
firstname5 = input()
print("write another first name")
firstname6 = input()
print("write another first name")
firstname7 = input()
print("write a plural noun")
pluralnoun3 = input()
### Tell the Madlib ###
print(" When we look up into the sky on a/an " + adjective1 + " summer night, we see millions of tiny spots of light.")
print(" Each one  represents a/an " + noun1)
print(" Wich is the center of a/an "+ adjective2)
print(" solar system with dozens of " + pluralnoun1 + " revolving " + adverb1 + " around a distant sun.")
print(" Sometimes these suns expand and begin " + verbing1 + " Their neighbors.")
print(" Soon they will become so big, they will turn into " + sillywordplural1 + ".")
print(" Eventually they subside and become " + adjective3)
print(" Giants or perhaps black" + pluralnoun2 + ".")
print(" Our own planet, which we call" +firstname1 + ".")
print(" Circles aroundour" + adjective4 + " Sun " + number1 + " times every year.")
print(" There are eight other planets in out solar system. They are named" + firstname2 + "," + firstname3 + "," + firstname4 + "," + firstname5 + "," + firstname6 + "," + firstname7 + " ,jupiter, and Mars.")
print(" Scientists who study these planets are called" + pluralnoun3)



time.sleep(200)
